# Generated by Django 4.2.3 on 2023-08-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisement', '0002_alter_advertisement_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
