# Generated by Django 4.2.3 on 2023-08-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisement', '0002_alter_advertisement_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default=0, upload_to='advertisement/', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
